"""initial schema

Revision ID: 53664ddb7e19
Revises: 
Create Date: 2026-07-18 03:58:05.729812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53664ddb7e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('level', sa.Float(), nullable=True),
    sa.Column('range_high', sa.Float(), nullable=True),
    sa.Column('range_low', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakout_events_detected_at'), 'breakout_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_breakout_events_symbol'), 'breakout_events', ['symbol'], unique=False)
    op.create_table('fair_value_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('gap_top', sa.Float(), nullable=False),
    sa.Column('gap_bottom', sa.Float(), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fair_value_gaps_detected_at'), 'fair_value_gaps', ['detected_at'], unique=False)
    op.create_index(op.f('ix_fair_value_gaps_symbol'), 'fair_value_gaps', ['symbol'], unique=False)
    op.create_table('liquidity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_events_detected_at'), 'liquidity_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_liquidity_events_symbol'), 'liquidity_events', ['symbol'], unique=False)
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('change_points', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_indices_symbol'), 'market_indices', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_indices_timestamp'), 'market_indices', ['timestamp'], unique=False)
    op.create_table('ohlcv_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ohlcv_symbol_tf_time', 'ohlcv_candles', ['symbol', 'timeframe', 'candle_time'], unique=False)
    op.create_table('options_chain_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('oi_current', sa.Float(), nullable=True),
    sa.Column('oi_change', sa.Float(), nullable=True),
    sa.Column('oi_change_percent', sa.Float(), nullable=True),
    sa.Column('price_close', sa.Float(), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('buildup_type', sa.String(length=24), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_chain_history_recorded_at'), 'options_chain_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_options_chain_history_underlying_symbol'), 'options_chain_history', ['underlying_symbol'], unique=False)
    op.create_table('options_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('previous_open_interest', sa.Float(), nullable=True),
    sa.Column('change_in_oi', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_options_contract_key', 'options_contracts', ['underlying_symbol', 'expiry_date', 'strike_price', 'option_type'], unique=False)
    op.create_index(op.f('ix_options_contracts_recorded_at'), 'options_contracts', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_options_contracts_underlying_symbol'), 'options_contracts', ['underlying_symbol'], unique=False)
    op.create_table('order_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('bottom', sa.Float(), nullable=False),
    sa.Column('mitigated', sa.Boolean(), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_blocks_detected_at'), 'order_blocks', ['detected_at'], unique=False)
    op.create_index(op.f('ix_order_blocks_symbol'), 'order_blocks', ['symbol'], unique=False)
    op.create_table('pcr_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('pcr_oi', sa.Float(), nullable=True),
    sa.Column('pcr_volume', sa.Float(), nullable=True),
    sa.Column('put_oi_total', sa.Float(), nullable=True),
    sa.Column('call_oi_total', sa.Float(), nullable=True),
    sa.Column('put_volume_total', sa.Float(), nullable=True),
    sa.Column('call_volume_total', sa.Float(), nullable=True),
    sa.Column('max_pain_level', sa.Float(), nullable=True),
    sa.Column('max_pain_direction', sa.String(length=16), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcr_analysis_recorded_at'), 'pcr_analysis', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_pcr_analysis_underlying_symbol'), 'pcr_analysis', ['underlying_symbol'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=True),
    sa.Column('bullish_score', sa.Float(), nullable=False),
    sa.Column('bearish_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=False),
    sa.Column('smart_money_score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('structure_bias', sa.String(length=24), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_recorded_at'), 'scan_results', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_scan_results_symbol'), 'scan_results', ['symbol'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('is_index', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('structure_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_events_detected_at'), 'structure_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_structure_events_symbol'), 'structure_events', ['symbol'], unique=False)
    op.create_table('volume_imbalances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('gap_top', sa.Float(), nullable=False),
    sa.Column('gap_bottom', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volume_imbalances_detected_at'), 'volume_imbalances', ['detected_at'], unique=False)
    op.create_index(op.f('ix_volume_imbalances_symbol'), 'volume_imbalances', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_imbalances_symbol'), table_name='volume_imbalances')
    op.drop_index(op.f('ix_volume_imbalances_detected_at'), table_name='volume_imbalances')
    op.drop_table('volume_imbalances')
    op.drop_index(op.f('ix_structure_events_symbol'), table_name='structure_events')
    op.drop_index(op.f('ix_structure_events_detected_at'), table_name='structure_events')
    op.drop_table('structure_events')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_scan_results_symbol'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_recorded_at'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_pcr_analysis_underlying_symbol'), table_name='pcr_analysis')
    op.drop_index(op.f('ix_pcr_analysis_recorded_at'), table_name='pcr_analysis')
    op.drop_table('pcr_analysis')
    op.drop_index(op.f('ix_order_blocks_symbol'), table_name='order_blocks')
    op.drop_index(op.f('ix_order_blocks_detected_at'), table_name='order_blocks')
    op.drop_table('order_blocks')
    op.drop_index(op.f('ix_options_contracts_underlying_symbol'), table_name='options_contracts')
    op.drop_index(op.f('ix_options_contracts_recorded_at'), table_name='options_contracts')
    op.drop_index('idx_options_contract_key', table_name='options_contracts')
    op.drop_table('options_contracts')
    op.drop_index(op.f('ix_options_chain_history_underlying_symbol'), table_name='options_chain_history')
    op.drop_index(op.f('ix_options_chain_history_recorded_at'), table_name='options_chain_history')
    op.drop_table('options_chain_history')
    op.drop_index('idx_ohlcv_symbol_tf_time', table_name='ohlcv_candles')
    op.drop_table('ohlcv_candles')
    op.drop_index(op.f('ix_market_indices_timestamp'), table_name='market_indices')
    op.drop_index(op.f('ix_market_indices_symbol'), table_name='market_indices')
    op.drop_table('market_indices')
    op.drop_index(op.f('ix_liquidity_events_symbol'), table_name='liquidity_events')
    op.drop_index(op.f('ix_liquidity_events_detected_at'), table_name='liquidity_events')
    op.drop_table('liquidity_events')
    op.drop_index(op.f('ix_fair_value_gaps_symbol'), table_name='fair_value_gaps')
    op.drop_index(op.f('ix_fair_value_gaps_detected_at'), table_name='fair_value_gaps')
    op.drop_table('fair_value_gaps')
    op.drop_index(op.f('ix_breakout_events_symbol'), table_name='breakout_events')
    op.drop_index(op.f('ix_breakout_events_detected_at'), table_name='breakout_events')
    op.drop_table('breakout_events')
    # ### end Alembic commands ###
